### ISSUE TITLE
When connection drops, P4SS begins to ask to check-out read/write files

### ISSUE THREAD

**Issue by ishani** [botman99/P4SimpleScc#3]
If my internet drops briefly or I lose connection to P4, I find that P4SS begins to ask if I want to check out files that are already checked-out and read/write - to the point where I can't actually write any code, it won't let me change the file and it can't talk to the P4 server to "check out" in the first place.

I would expect it not to bother asking if the file is not read-only

**Comment by botman99** [comment]
Yeah, I've had times in the past where my VPN connection drops and it can't connect to the server.  I don't rely on read-only file status because you could have the Perforce workspace set to make all files writeable (even though they aren't checked out) and Visual Studio wouldn't know if the file needs to be checked out or not.

I'm not sure there's a good solution to this problem.  I could add an option to make the file writable, but it still won't be checked out from Perforce and you'd have to remember to do a "Reconcile Offline Work" later to add the modified files to a pending changelist.  I would prefer to get an error dialog (as you mentioned) as a notification that something is wrong and then fix whatever the problem is before modifying the file.

You could also just set the file writeable in Windows Explorer and then modify the file as long as you remember to reconcile the offline change later after restoring the connection to the Perforce server.

**Comment by Daxou** [comment]
Hey :)
A bit late to the party but I made an update on my fork to add an option to not do any checkouts operation on files that are not readonly. I have this exact issue with a lot of connections lost and a lot of freezes in VS.
Would you be interested in adding it in the official version?

**Comment by botman99** [comment]
I'll take a look and see what you have.  I had thought about chaging this a while back to deal with the case of a workspace that is not set to "allwrite" to look at the read-only status of the file first before trying to check with the server.  You don't really need an option for this, it would be the default behavior.  You would still not be able to modify files that weren't checked out without connecting to the server first.  You could make the file writeable locally, but you'd have to remember to use "Reconcile Offline Work" later to make sure that files you modified while not connected get properly added back to the server later.

**Comment by Daxou** [comment]
I'm still doing a couple more tests and I should be able to send a request by end of week

**Comment by botman99** [comment]
This was fairly trivial, in P4Command.cs the ServerConnect() function reads the clientspec (with "client -o") and it checks "Access:" and "Root:", it just needs to check "Options:" to see if it contains "noallwrite".  If so, set a bool somewhere to true to indicate that files should be read-only when not checked out.  Then in SccProvider.cs in the IsCheckedOut() function, if the noallwrite bool is true, just check if the file is not read-only and return true there.

**Comment by Daxou** [comment]
That's pretty much what I did but I didn't want to throw you a request without testing it.
I also added the check in the checkout function itself because if I remember it was sometimes called as well without the check before

**Comment by botman99** [comment]
I went ahead and commited my change for checking the client for "notallwrite" and skip checking out files if they are not read-only here...

https://github.com/botman99/P4SimpleScc/commit/dcb6fc99e832490fb518fa5b961e6063bb7dab6f

**Comment by botman99** [comment]
I'll do a little more testing and release this change as well as update the Microsoft Marketplace extension this weekend.

**Comment by Daxou** [comment]
Awesome, thanks, you are too fast. Sorry I've been really busy and didn't get the time to send you the request like I said I would.
